# Service account to access the kubernetes API
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include ".fullname" . }}-controller
---
# Role that the Container can access the Kubernetes API
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include ".fullname" . }}-pod-get-delete
rules:
- apiGroups: [ "" ]
  resources: [ "pods" ]
  verbs:
  - get
  - list
  - watch
  - delete
  - create
  - patch
- apiGroups: [ "batch" ]
  resources: [ "jobs" ]
  verbs:
  - create
  - list
  - patch
---
# Assign the role to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include ".fullname" . }}-pod-get-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include ".fullname" . }}-pod-get-delete
subjects:
- kind: ServiceAccount
  name: {{ include ".fullname" . }}-controller