apiVersion: v1
kind: Service
metadata:
  name: {{ include ".fullname" . }}-service
spec:
  type: ClusterIP
  selector:
    app: {{ include ".fullname" . }}-controller
  ports:
  - protocol: TCP
    port: 4020
    targetPort: 4020